### ISSUE TITLE
Hardcoding tests for printing of random data is brittle

### ISSUE THREAD

**Issue by KristofferC** [JuliaEarth/GeoStatsFunctions.jl#7]
Tests fail on 1.11 due to:

https://github.com/JuliaEarth/GeoStatsFunctions.jl/blob/59c4da62cdada21dbed0544bf619ad90692511b4/test/empirical.jl#L49-L60

which tests how some random data is printed.

**Comment by juliohm** [comment]
Thank you, will take a look.
